### ISSUE TITLE
im getting an error

### ISSUE THREAD

**Issue by mavdotj** [willassad/cryptocurrencypython#1]
[EnvCommandError]
Command ['/opt/virtualenvs/python3/bin/pip', 'install', '--no-deps', 'mysqlclient==2.0.3'] errored with the following return code 1, and output: 
Collecting mysqlclient==2.0.3
  Using cached https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/virtualenvs/python3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fo99ih0e/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fo99ih0e/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fo99ih0e/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-fo99ih0e/mysqlclient/
    Complete output (15 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fo99ih0e/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-fo99ih0e/mysqlclient/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-fo99ih0e/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by willassad** [comment]
Try updating setup tools `pip install -U setuptools`

**Comment by Imran407704** [comment]
I got an error  Please Help 
![sqlhelper error 2](https://user-images.githubusercontent.com/51431951/138076814-af33086a-dc1d-433f-8126-d25b5a1a28f3.png)
![sqlhelper error 3](https://user-images.githubusercontent.com/51431951/138076821-a4808011-dada-4200-8f8f-a6c875c96ef9.png)
![sqlhelper error](https://user-images.githubusercontent.com/51431951/138076823-043e0232-7ecb-4b61-acc1-a6b1dd250be8.png)

**Comment by mavdotj** [comment]
such bad issue naming me from 6mo ago

**Comment by mavdotj** [comment]
Such bad necroposting from me 2 years ago
